version: '3.9'
services:
  app:
    build: .
    ports:
      - '8000:4000'
    environment:
      POSTGRES_DNS: ${POSTGRES_DNS}
    depends_on:
      - postgresql
  postgresql:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'welsh'
