version: '3.9'
services:
  app:
    build:
      context: ./..
      dockerfile: docker/Dockerfile.test
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: welsh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
